sap/urls.py
#coding: utf-8
from django.conf.urls import patterns, url
from sap import views
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
urlpatterns = patterns('',
                       url(r'^$', views.user_login, name='index'),
                       #Admin
                       url(r'^index_professor',views.index_professor, name='index_professor'),
                       url(r'^index_aluno',views.index_aluno, name='index_aluno'),
                       url(r'^admin',views.admin, name='admin'),
                       url(r'^register_professor',views.register_professor, name='register_professor'),
                       url(r'^register_aluno',views.register_aluno, name='register_aluno'),
                       url(r'^adicionar_diciplina',views.adicionar_diciplina, name='adicionar_diciplina'),
                       url(r'^adicionar_disciplina_aluno',views.adicionar_disciplina_aluno, name='adicionar_disciplina_aluno'),
                       url(r'^relatorio_professor',views.relatorio_professor, name='relatorio_professor'),
                       url(r'^login',views.user_login, name='login'),
                       url(r'^logout',views.user_logout, name='logout'),
                       #Professor
                       url(r'^criar_dissertativa',views.criar_dissertativa, name='criar_dissertativa'),
                       url(r'^criar_multipla_escolha',views.criar_multipla_escolha, name='criar_multipla_escolha'),
                       url(r'^criar_verdadeiro_falso',views.criar_verdadeiro_falso, name='criar_verdadeiro_falso'),
                       url(r'^editar_questao',views.editar_questao, name='editar_questao'),
                       url(r'^criar_avaliacao',views.criar_avaliacao, name='criar_avaliacao'),
                       url(r'^adicionar_remover_pergunta/(?P<avaliacao>[\w\-]+)',views.adicionar_remover_pergunta, name='adicionar_remover_pergunta'),
                       url(r'^alterar_dados_avaliacao/(?P<avaliacao>[\w\-]+)',views.alterar_dados_avaliacao, name='alterar_dados_avaliacao'),
                       url(r'^editar_avaliacao',views.editar_avaliacao, name='editar_avaliacao'),
                       url(r'^corrigir_avaliacao',views.corrigir_avaliacao, name='corrigir_avaliacao'),
                       url(r'^vizualizar_avaliacao',views.vizualizar_avaliacao, name='vizualizar_avaliacao'),
                       url(r'^visualizar_gabarito', views.visualizar_gabarito, name='visualizar_gabarito'),
                       url(r'^correcao_questao/(?P<avaliacao>[\w\-]+)',views.correcao_questao, name='correcao_questao'),
                       url(r'^correcao_aluno/(?P<avaliacao>[\w\-]+)',views.correcao_aluno, name='correcao_aluno'),
                       url(r'^relatorio_professor',views.relatorio_professor, name='relatorio_professor'),
                       url(r'^reaplicar_avaliacao',views.reaplicar_avaliacao, name='reaplicar_avaliacao'),
                       url(r'^excluir_avaliacao',views.excluir_avaliacao, name='excluir_avaliacao'),
                       url(r'^excluir_questao',views.excluir_questao, name='excluir_questao'),
                       url(r'^serverTime',views.serverTime, name='serverTime'),


                       #Aluno
                       url(r'^realizar_avaliacao',views.realizar_avaliacao, name='realizar_avaliaçao'),
                       url(r'^notas',views.notas, name='notas'),
                       url(r'^avaliacao',views.avaliacao, name='avaliacao'),
                       url(r'^sair_safeexam',views.sair_safeexam, name='sair_safeexam'),

                       )

sapu/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sapu.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^sap/', include('sap.urls')),
)

from django.conf import settings


if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

sap/models.py
#coding: utf-8

import datetime
from django.db import models
from django.contrib.auth.models import User, Group
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

class Alunos(User):
    class Meta:
        verbose_name_plural = 'Alunos'
    def __unicode__(self):
        return self.username
class Disciplina(models.Model):
    nome = models.CharField(max_length=250)
    disciplina = models.ManyToManyField(Alunos,'Disciplina_has_alunos')
    def __unicode__(self):
        return self.nome
class Disciplina_has_aluno(models.Model):
    disciplina = models.ForeignKey('Disciplina')
    aluno = models.ForeignKey('Alunos')
class Professores(User):
    class Meta:
        verbose_name_plural = 'Professores'
class Tipo(models.Model):
    tipo = models.CharField(max_length=250)
    def __unicode__(self):
        return self.tipo

class Questoes(models.Model):
    tipo = models.ForeignKey('Tipo')
    professor = models.ForeignKey('Professores')
    disciplina = models.ManyToManyField('Disciplina')
    enunciado = models.TextField(max_length=5000, unique=False)
    a = models.TextField(max_length=5000, unique=False, blank=True)
    b = models.TextField(max_length=5000, unique=False, blank=True)
    c = models.TextField(max_length=5000, unique=False, blank=True)
    d = models.TextField(max_length=5000, unique=False, blank=True)
    e = models.TextField(max_length=5000, unique=False, blank=True)
    resposta_correta = models.TextField(max_length=5000, unique=False)
    imagem = models.ImageField(upload_to='questao_imagem',blank=True)

    def __unicode__(self):
        return self.enunciado

class Avaliacao(models.Model):
    professor = models.ForeignKey('Professores')
    nome = models.CharField(max_length=250)
    data_hora_inicio = models.DateTimeField(auto_now=False)
    data_hora_fim = models.DateTimeField(auto_now=False)
    senha = models.CharField(max_length=20)
    questao = models.ManyToManyField(Questoes,through='Avaliacao_has_questoes')
    disciplina = models.ForeignKey('Disciplina')
    SafeExamBrowser = models.BooleanField(default=False)
    Mostrar_Respostas = models.BooleanField(default=False)
    imagem = models.ImageField(upload_to='avaliacao_imagem',blank=True)



    def __unicode__(self):
        return self.nome
class Avaliacao_has_questoes(models.Model):
    avaliacao = models.ForeignKey('Avaliacao')
    questao = models.ForeignKey('Questoes')
    peso = models.FloatField(default=1)
    ordem = models.IntegerField(default=0)
    aluno = models.ManyToManyField(Alunos,'Respostas')

    def __unicode__(self):
        return unicode(self.questao)
class Respostas(models.Model):
    aluno = models.ForeignKey('Alunos')
    avaliacao_has_questoes = models.ForeignKey('Avaliacao_has_questoes')
    resposta_correta = models.TextField(max_length=5000, unique=False)
    pontuacao = models.FloatField(default=0)

    def __unicode__(self):
        return self.resposta_correta

class Aluno_has_avaliacao(models.Model):
    aluno = models.ForeignKey('Alunos')
    avaliacao = models.ForeignKey('Avaliacao')
    data_hora = models.DateTimeField(auto_now=True)
    nota_final = models.FloatField(default=0)

sap/forms/Avaliacao_has_questoesForm.py
#coding: utf-8
from django import forms
from django.contrib.auth.models import User, Group
from sap.models import *
from sap.views import *
from datetime import date
from django.forms.extras.widgets import *
from datetimewidget.widgets import DateTimeWidget, DateWidget, TimeWidget

import user
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

class Avaliacao_has_questoesForm(forms.ModelForm):
    class Meta:
        model = Avaliacao_has_questoes
        fields = ('avaliacao', 'peso', 'ordem', 'questao')
        exclude = ("aluno",)
        widgets = {'questao':forms.CheckboxSelectMultiple(),}

    def __init__(self, user=None, **kwargs):
        super(Avaliacao_has_questoesForm, self).__init__(**kwargs)
        if user:
            self.fields['avaliacao'].queryset = Avaliacao.objects.filter(professor= user.id)
            self.fields['questao'].queryset = Questoes.objects.filter(professor= user.id)

sap/forms/RegAluno.py
#coding: utf-8
from django import forms
from django.contrib.auth.models import User, Group
from sap.models import *
from sap.views import *
from datetime import date
from django.forms.extras.widgets import *
from datetimewidget.widgets import DateTimeWidget, DateWidget, TimeWidget

import user
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

class RegAluno(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Alunos
        fields = ('username', 'password')

sap/forms/RegProfessor.py
#coding: utf-8
from django import forms
from django.contrib.auth.models import User, Group
from sap.models import *
from sap.views import *
from datetime import date
from django.forms.extras.widgets import *
from datetimewidget.widgets import DateTimeWidget, DateWidget, TimeWidget

import user
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

class RegProfessor(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Professores
        fields = ('username', 'password')

sap/forms/TypeUserForm.py
#coding: utf-8
from django import forms
from django.contrib.auth.models import User, Group
from sap.models import *
from sap.views import *
from datetime import date
from django.forms.extras.widgets import *
from datetimewidget.widgets import DateTimeWidget, DateWidget, TimeWidget

import user
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

class TypeUserForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('name',)

sap/forms/correcaoForm.py
#coding: utf-8
from django import forms
from django.contrib.auth.models import User, Group
from sap.models import *
from sap.views import *
from datetime import date
from django.forms.extras.widgets import *
from datetimewidget.widgets import DateTimeWidget, DateWidget, TimeWidget

import user
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

class correcaoForm(forms.ModelForm):
    class Meta:
        model = Respostas
        fields = ("pontuacao",)

sap/views/adicionar_diciplina.py
#coding: utf-8

import user
from django.http import HttpResponse
from django.shortcuts import render, redirect
from sap.models import *
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import Group
from sap.forms import *
from check_professor import *
from check_aluno import *
from django.db.models import Sum
import datetime
from django_user_agents.utils import *
reload(sys)
sys.setdefaultencoding('utf-8')
@login_required()
@user_passes_test(check_professor, login_url='login.html')
def adicionar_diciplina(request):
    context_dict = {}
    if request.method != "POST":
        diciplina_form = diciplinaForm()
    else:
        diciplina_form = diciplinaForm(data=request.POST)
        if diciplina_form.is_valid():
            nome = diciplina_form.save()
            nome.save()

    context_dict['diciplina_form'] = diciplina_form
    template ='sap/adicionar_diciplina.html'
    return render(request, template , context_dict)

sap/views/adicionar_disciplina_aluno.py
#coding: utf-8

import user
from django.http import HttpResponse
from django.shortcuts import render, redirect
from sap.models import *
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import Group
from sap.forms import *
from django.db.models import Sum
import datetime
from check_professor import *
from check_aluno import *
from django_user_agents.utils import *
reload(sys)
sys.setdefaultencoding('utf-8')
@login_required()
@user_passes_test(check_professor, login_url='login.html')
def adicionar_disciplina_aluno(request):
    context_dict = {}
    if request.method != "POST":
        form = disciplina_has_alunoForm()
    else:
        form = disciplina_has_alunoForm(data=request.POST)
        if form.is_valid():
            nome = form.save()
            nome.save()
    context_dict['form'] = form
    template ='sap/adicionar_disciplina_aluno.html'
    return render(request, template , context_dict)

sap/views/adicionar_remover_pergunta.py
#coding: utf-8

import user
from django.http import HttpResponse
from django.shortcuts import render, redirect
from sap.models import *
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import Group
from sap.forms import *
from check_professor import *
from check_aluno import *
from django.db.models import Sum
import datetime
from django_user_agents.utils import *
reload(sys)
sys.setdefaultencoding('utf-8')
@login_required()
@user_passes_test(check_professor, login_url='login.html')
def adicionar_remover_pergunta(request, avaliacao):
    context_dict = {}
    context_dict['avaliacao'] = avaliacao
    if request.method != "POST":
        try:
            Avaliacao.objects.get(id= avaliacao, professor= request.user)
            existe = Aluno_has_avaliacao.objects.filter(avaliacao= avaliacao).exists()
            a = Avaliacao.objects.get(id= avaliacao)
            if existe == True or a.data_hora_inicio < datetime.datetime.now() and a.data_hora_fim > datetime.datetime.now():
                context_dict['vazio'] = "Você não pode editar esta avaliação."
            else:
                questoes_inclusas = Avaliacao_has_questoes.objects.filter(avaliacao= Avaliacao.objects.get(id= avaliacao)).order_by('ordem')
                questoes_inclusas2 = Questoes.objects.filter(avaliacao= avaliacao)
                avaliacaoob = Avaliacao.objects.get(id= avaliacao)
                questoes_nao_inclusas = Questoes.objects.filter(professor = request.user, disciplina= avaliacaoob.disciplina).exclude(id__in= questoes_inclusas2).order_by()
                context_dict['questoes_nao_inclusas'] = questoes_nao_inclusas
                context_dict['questoes_inclusas'] = questoes_inclusas

        except:
            context_dict['vazio'] = "Você não pode editar esta avaliação."
    else:
        excluir = request.POST.getlist('excluir')
        adicionar = request.POST.getlist('adicionar')
        peso = filter(None,request.POST.getlist('peso'))
        ordem = filter(None,request.POST.getlist('ordem'))
        print excluir
        if excluir or adicionar:
            if excluir:
                for x in range(0,len(excluir)):
                    try:
                        Avaliacao_has_questoes.objects.get(avaliacao= (Avaliacao.objects.get(id= avaliacao)), questao= Questoes.objects.get(id= excluir[x])).delete()
                    except:
                        return redirect('/sap/index_professor.html')
                context_dict['excluidas'] = Questoes.objects.filter(id__in= excluir)
            if adicionar:
                for x in range(0,len(adicionar)):
                    Avaliacao_has_questoes.objects.get_or_create(avaliacao= (Avaliacao.objects.get(id= avaliacao)), questao= Questoes.objects.get(id= adicionar[x]),peso= peso[x], ordem= ordem[x])
                context_dict['adicionadas'] = Questoes.objects.filter(id__in= adicionar)
                ordem = Avaliacao_has_questoes.objects.filter(avaliacao= (Avaliacao.objects.get(id= avaliacao))).values_list('ordem', flat= True)
                questoes = Avaliacao_has_questoes.objects.filter(avaliacao= (Avaliacao.objects.get(id= avaliacao))).values_list('questao', flat= True)
                #Criar função \/
                conv = []
                for item in ordem:
                    conv.append(int(item))
                ordem = conv
                na= len(ordem)
                nova_lista = list(set(ordem))
                nnova_list = len(nova_lista)
                print ordem, na, nova_lista, nnova_list
                if na != nnova_list:
                    for v in range (len(nova_lista), (na)):
                        nova_lista.append(int(max(nova_lista)) + 1)
                    ordem = nova_lista
                    print ordem
                    questoes = sorted(questoes)
                    print questoes
                    #Criar função /\
                    for v in range (0,int(len(ordem))):
                        Avaliacao_has_questoes.objects.filter(avaliacao= Avaliacao.objects.get(id= avaliacao), questao= questoes[v]).update(ordem= ordem[v])

        else:
             context_dict['sem_selecao'] = "Você deve selecionar ao menos uma questão"

    template ='sap/adicionar_remover_pergunta.html'
    return render(request, template , context_dict)

sap/views/admin.py
#coding: utf-8

import user
from django.http import HttpResponse
from django.shortcuts import render, redirect
from sap.models import *
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import Group
from sap.forms import *
from check_professor import *
from check_aluno import *
from django.db.models import Sum
import datetime
from django_user_agents.utils import *
reload(sys)
sys.setdefaultencoding('utf-8')
@login_required()
@user_passes_test(check_professor, login_url='login.html')
def admin(request):
    context_dict = {}
    template ='sap/admin.html'
    return render(request, template , context_dict)

templates/sap/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
</br><a href="/sap/register_aluno/">Cadastrar Aluno</a><br/>
</br><a href="/sap/register_professor/">Cadastrar Professor</a><br/>
</br><a href="/sap/adicionar_diciplina/">Adicionar Diciplina</a><br/>
</br><a href="/sap/adicionar_disciplina_aluno/">Adicionar aluno em uma disciplina</a><br/>



</body>
</html>

templates/sap/aplicar_avaliacao.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static "js/jquery.datetimepicker.css"%}"/>
    <script src="{% static "js/jquery-1.11.3.js" %}"></script>
    <script src="{% static "js/base.js"%}"></script>
    <script src="{% static "js/jquery.js"%}"></script>
    <script src="{% static "js/build/jquery.datetimepicker.full.min.js"%}"></script>
</head>
<body>
<h1> Aplicar avaliacao</h1>
    <form id="turma_has_avaliacaoform" method="post" action="/sap/aplicar_avaliacao/">
    {% csrf_token %}
    {{ turma_has_avaliacaoform.as_p }}

    <input type="submit" name="submit" value="Adicionar">

</form>
</body>

</html>

templates/sap/base_aluno.html
<!DOCTYPE html>
{% load staticfiles %}



<script src="{% static "js/jquery-1.11.3.js" %}"></script>
<script src="{% static "js/rango-ajax.js" %}"></script>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" ="">

    <link href="{%  static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{%  static 'css/dashboard.css' %}" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header ">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand " href="/sap/index_aluno/">Home </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#/">Ola, {{ request.user }}</a></li>
                <li><a href="/sap/logout/">Sair</a></li>


            </ul>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            {% block side_block %}
                <ul class="nav nav-list">

                    <li><a href="/sap/realizar_avaliacao/">Iniciar avaliação</a></li>
                    <li><a href="/sap/notas/">Visualizar notas</a></li>

                </ul>
            {% endblock %}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <div>
                {% block body_block %}{% endblock %}
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

templates/sap/editar_questao.html
{% extends 'sap/base_professor.html' %}

{% block body_block %}

    <h3 class="text-left text-info">
        Editar questão</h3>

    {% if sucess %}
        {{ sucess }}

    {% elif falha %}
        {{ falha }}

    {% elif dissertativa %}
        <form id="formdissertativa" method="post" action="/sap/editar_questao" enctype="multipart/form-data">
            {% csrf_token %}
            <input id="id_professor" name="professor" type="hidden" value={{ request.user.id }}>
            <label> Enunciado:</label> <br>
            <textarea cols="40" id="id_enunciado" name="enunciado" rows="10">{{ dissertativa.enunciado }}</textarea>
            <br>
            <label>
                Resposta:
            </label> <br>
            <textarea cols="40" id="id_resposta_correta" name="resposta_correta" rows="10">{{ dissertativa.resposta_correta }}</textarea>
            <br>
            <label> Imagem: </label><br>
            <input id="id_imagem" name="imagem" type="file"> <br>
            {% if dissertativa.imagem %}
                <img src="/media/{{ dissertativa.imagem }}"  />
                <br><br>
                <input type="submit" class="btn btn-default" name="deletar" value="Deletar" /> <br>
                <br>
            {% endif %}
            <label>
                Selecione as disciplinas para as quais essa questão se aplica:
            </label> <br>
            {% for d in diciplinas_questao %}
                <input id="checkbox{{forloop.counter}}" type="checkbox" name="disciplina" autocomplete="off" checked value={{ d.id }}> {{ d.nome }} </br>
            {% endfor %}

            {% for d in disciplinas_n_questao %}
                <input id="checkbox{{forloop.counter}}" type="checkbox" name="disciplina" autocomplete="off" value={{ d.id }}> {{ d.nome }} </br>
            {% endfor %}
            </br>
            <input type="hidden" name="{{ dissertativa.tipo }}" value="{{ dissertativa.tipo }}">
            <input type="hidden" name="questaon" value="{{ dissertativa.id }}">
            <input type="submit" class="btn btn-default" name="submit" value="Alterar" />
        </form>

    {% elif multipla_escolha %}
        <form id="formmultipla_escolha" method="post" action="/sap/editar_questao/" enctype="multipart/form-data">
            <div class="form-group">
                {% csrf_token %}
                <input id="id_professor" name="professor" type="hidden" value="0" />
                <label> Enunciado: </label> </br>

                <textarea cols="40" id="id_enunciado" maxlength="5000" name="enunciado" rows="10">{{ multipla_escolha.enunciado }}</textarea>
                </br>

                <label> A: </label> </br>
                <textarea cols="40" id="id_a" name="a" rows="10">{{ multipla_escolha.a }}</textarea>

                </br>
                <label> B: </label> </br>
                <textarea cols="40" id="id_b" name="b" rows="10">{{ multipla_escolha.b }}</textarea>

                </br>
                <label> C: </label> </br>
                <textarea cols="40" id="id_c" name="c" rows="10">{{ multipla_escolha.c }}</textarea>

                </br>
                <label> D: </label> </br>
                <textarea cols="40" id="id_d" name="d" rows="10">{{ multipla_escolha.d }}</textarea>

                </br>
                <label> E: </label> </br>
                <textarea cols="40" id="id_e" name="e" rows="10">{{ multipla_escolha.e }}</textarea>

                </br>
                <label>
                    Resposta Correta
                </label> </br>
                <select name="resposta_correta" value="{{ multipla_escolha.resposta_correta }}"></br>

                    <option value="A" {% if multipla_escolha.resposta_correta == 'A' %} selected {% endif %}>A</option>
                    <option value="B" {% if multipla_escolha.resposta_correta == 'B' %} selected {% endif %}>B</option>
                    <option value="C" {% if multipla_escolha.resposta_correta == 'C' %} selected {% endif %}>C</option>
                    <option value="D" {% if multipla_escolha.resposta_correta == 'D' %} selected {% endif %}>D</option>
                    <option value="E" {% if multipla_escolha.resposta_correta == 'E' %} selected {% endif %}>E</option>

                </select> </br>
                <label> Imagem: </label><br>
                <input id="id_imagem" name="imagem" type="file"> <br>
                {% if multipla_escolha.imagem %}
                    <p>Imagem atual:</p>
                    <img src="/media/{{ multipla_escolha.imagem }}"  />
                    <br><br>
                    <input type="submit" class="btn btn-default" name="deletar" value="Deletar" /> <br>
                {% endif %}
                <label>
                    Selecione as disciplinas para as quais essa questão se aplica:
                </label> </br>
                {% for d in diciplinas_questao %}
                    <input id="checkbox{{forloop.counter}}" type="checkbox" name="disciplina" autocomplete="off" checked value={{ d.id }}> {{ d.nome }} </br>
                {% endfor %}

                {% for d in disciplinas_n_questao %}
                    <input id="checkbox{{forloop.counter}}" type="checkbox" name="disciplina" autocomplete="off" value={{ d.id }}> {{ d.nome }} </br>
                {% endfor %}
                </br>

                <input type="hidden" name="{{ multipla_escolha.tipo }}" value="{{ dissertativa.tipo }}">
                <input type="hidden" name="questaon" value="{{ multipla_escolha.id }}">
                <input type="submit" class="btn btn-default" name="submit" value="Alterar" />
            </div>
        </form>

    {% elif questoes %}
        <p>Selecione a questão:</p>
        </br>
        <form id="alterar_dados_avaliacao" method="post" action="/sap/editar_questao">
            {% csrf_token %}
                {% for d in questoes %}
                      <input type="radio" name="questao" value="{{ d.id }}" checked> {{ d.enunciado}} - {{ d.tipo }} <hr>
                {% endfor %}
            <input type="submit" class="btn btn-default" name="submit" value="Selecionar" />
        </form>

    {% else %}
        <p> Selecione a disciplina que deseja editar. </p>
        </br>
        <form id="editar_questao" method="post" action="/sap/editar_questao/">
            {% csrf_token %}
            <select name="disciplina" class="btn btn-default">
                {% for d in disciplina %}
                    <option value="{{ d.id }}">{{ d.nome}}</option>
                {% endfor %}
            </select>
            <input type="submit" class="btn btn-default" name="submit" value="Selecionar" />
        </form>

    {% endif %}

{% endblock body_block %}

templates/sap/index_aluno.html
{% extends 'sap/base_aluno.html' %}

{% block body_block %}

{% endblock body_block %}

templates/sap/index_professor.html
{#<!DOCTYPE html>#}
{#{% load static %}#}
{#<html>#}
{##}
{#    <head>#}
{#        <title>Sap</title>#}
{#    </head>#}
{##}
{#    <body>#}

{% extends 'sap/base_professor.html' %}

{% block body_block %}
{#    <h3 class="text-left text-info">#}
{#    Professor</h3>#}
    {{ navegador }}
{% endblock body_block %}

{#</html>#}

templates/sap/sair_safeexam.html
<!DOCTYPE html>
{% load static %}
<html>

    <head>
        <title>Sap</title>
    </head>

    <body>
    <h1>Sair </h1>

    </body>

</html>

templates/sap/serverTime.html
{{ data_atual }}